VIA_ENABLE = yes
VIAL_ENABLE = yes

RGB_MATRIX_ENABLE		= yes
RGB_MATRIX_DRIVER		= WS2812
VIALRGB_ENABLE 			= yes
RGB_MATRIX_CUSTOM_USER  = yes
AUDIO_ENABLE 			= yes
AUDIO_DRIVER 			= pwm_hardware

MIDI_ENABLE = no